version: "3.9"

services:
  mysql:
    container_name: mysql_libreria
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_libreria:/var/lib/mysql
    environment:
      MYSQL_DATABASE: libreria
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_libreria: